tap "anomalyco/tap"
tap "homebrew/cask"
tap "minicodemonkey/chief"
brew "libpng"
brew "libtiff"
brew "little-cms2"
brew "openexr"
brew "webp"
brew "jpeg-xl"
brew "apr-util"
brew "autoconf"
brew "btop"
brew "freetype"
brew "pcre2"
brew "glib"
brew "cmake"
brew "unixodbc"
brew "freetds"
brew "libavif"
brew "gd"
brew "libsodium"
brew "php"
brew "composer"
brew "dnsmasq"
brew "fastfetch"
brew "fribidi"
brew "gnutls"
brew "harfbuzz"
brew "tesseract"
brew "ffmpeg"
brew "gcc"
brew "gdbm"
brew "gh"
brew "git-flow"
brew "libgcrypt"
brew "libksba"
brew "gnupg"
brew "go"
brew "pkgconf"
brew "hdf5"
brew "jpeg"
brew "kubectx"
brew "mas"
brew "mkcert"
brew "mpdecimal"
brew "nvm"
brew "perl"
brew "php@8.2"
brew "pyenv"
brew "pyenv-virtualenv"
brew "python@3.10"
brew "qemu"
brew "rbenv"
brew "starship"
brew "thefuck"
brew "tree"
brew "uv"
brew "wget"
brew "yarn"
brew "anomalyco/tap/opencode"
brew "minicodemonkey/chief/chief"
cask "apparency"
cask "boop"
cask "bruno"
cask "claude"
cask "claude-code"
cask "discord"
cask "dotnet-sdk"
cask "elgato-camera-hub"
cask "elgato-control-center"
cask "elgato-stream-deck"
cask "elgato-wave-link"
cask "font-fira-code-nerd-font"
cask "ghostty"
cask "godot-mono"
cask "jetbrains-toolbox"
cask "monitorcontrol"
cask "ngrok"
cask "obs"
cask "obsidian"
cask "orbstack"
cask "rectangle"
cask "slack"
cask "steam"
cask "thaw"
cask "tunnelbear"
cask "whatsapp"
cask "zed"
cask "zen"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator Pro", id: 1289583905
mas "Steam Link", id: 1246969117
mas "Swift Playground", id: 1496833156
mas "Xcode", id: 497799835
